dependencies:
  
  # Contoh dependensi lainnya
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.8
  path_provider: ^2.0.11 # Untuk mendapatkan path aplikasi
  provider: ^6.0.0 # Untuk state management
  sqflite: ^2.4.1
  # Anda bisa menambahkan dependensi lain sesuai kebutuhan


# Daftar dependensi yang digunakan dalam proyek
description: A simple voting app

# Mengatur versi minimum Dart yang digunakan
dev_dependencies:
  flutter_test:
    sdk: flutter
environment:
  sdk: ">=2.19.0 <3.0.0"


# Daftar dependensi yang digunakan dalam proyek
flutter:
  assets:
    - assets/images/
name: vote_app
# Pengaturan assets, seperti gambar dan font, bisa ditambahkan di bawah sini


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
vote_app: ^2.0.0+4  # Untuk SQLite database  # Anda bisa menambahkan dependensi lain sesuai kebutuhan
